services:
  - type: web
    name: enhanced-chat-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        fromDatabase:
          name: enhanced-chat-db
          property: connectionString
      - key: CLERK_SECRET_KEY
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: https://enhanced-chat-frontend.onrender.com

  - type: web
    name: enhanced-chat-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_API_URL
        value: https://enhanced-chat-backend.onrender.com
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false

databases:
  - name: enhanced-chat-db
    databaseName: enhanced_chat
    user: enhanced_chat_user
